# Generated by Django 2.2.7 on 2019-11-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191129_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status', 'due_back', 'id'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
